# Enable touchpad tap
xinput set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

# Map F{10,11,12} to Vol{Mute,Down,Up}
xmodmap ~/.Xmodmap

# Colors and etc
xrdb ~/.Xresources

WM='kde'

case $WM in
	'i3')
		xrandr --auto
		feh --bg-fill ~/Pictures/.wallpaper
		exec i3
		;;
	'kde')
		exec startkde
		;;
esac

