actions:
  dunst-run: pkill dunst && i3-msg exec dunst
  i3-run: i3-msg restart; while ! i3-msg; do echo 'waiting for i3, the error msg above
    is normal'; done
  polybar-run: pkill polybar && i3-msg exec polybar top
  pre:
    plug: nvim +PlugInstall +qall
    plug-inst: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
dotfiles:
  d_homepage:
    dst: ~/.config/homepage
    src: config/homepage
  d_scripts:
    dst: ~/.scripts
    src: scripts
  d_templates:
    dst: ~/.config/wpg/templates
    src: config/wpg/templates
  d_util:
    dst: ~/.scripts/util
    src: scripts/util
  f_album-pic.sh:
    dst: ~/.scripts/util/album-pic.sh
    src: scripts/util/album-pic.sh
  f_bindings:
    dst: ~/.config/ncmpcpp/bindings
    src: config/ncmpcpp/bindings
  f_blur.sh:
    dst: ~/.scripts/images/blur.sh
    src: scripts/images/blur.sh
  f_cava_config:
    dst: ~/.config/cava/config
    src: config/cava/config
  f_compton.conf:
    dst: ~/.compton.conf
    src: compton.conf
  f_config:
    actions:
    - i3-run
    dst: ~/.config/i3/config
    src: config/i3/config
  f_dunstrc:
    actions:
    - dunst-run
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_filer.sh:
    dst: ~/.scripts/util/filer.sh
    src: scripts/util/filer.sh
  f_index.html:
    dst: ~/.config/homepage/index.html
    src: config/homepage/index.html
  f_init.vim:
    actions:
    - plug-inst
    - plug
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_input.conf:
    dst: ~/.config/mpv/input.conf
    src: config/mpv/input.conf
  f_lock:
    dst: ~/.scripts/util/lock
    src: scripts/util/lock
  f_mpv.conf:
    dst: ~/.config/mpv/mpv.conf
    src: config/mpv/mpv.conf
  f_music.json:
    dst: ~/.config/i3/music.json
    src: config/i3/music.json
  f_ncmpcpp_config:
    dst: ~/.config/ncmpcpp/config
    src: config/ncmpcpp/config
  f_pkgbuild:
    dst: ~/.config/st/PKGBUILD
    src: config/st/PKGBUILD
  f_polybar_config:
    actions:
    - polybar-run
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_profile-switch.sh:
    dst: ~/.scripts/util/profile-switch.sh
    src: scripts/util/profile-switch.sh
  f_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_rice.sh:
    dst: ~/.scripts/util/rice.sh
    src: scripts/util/rice.sh
  f_rifle.conf:
    dst: ~/.config/ranger/rifle.conf
    src: config/ranger/rifle.conf
  f_style.css:
    dst: ~/.config/homepage/style.css
    src: config/homepage/style.css
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  the-arch:
    dotfiles:
    - ALL
  work:
    include:
    - the-arch
  mac:
    include:
    - work
  rice:
    include:
    - work
