actions:
  dunst-run: pkill dunst && i3-msg exec dunst
  i3-run: i3-msg restart; while ! i3-msg; do echo 'waiting for i3, the error msg above
    is normal'; done
  polybar-run: pkill polybar && i3-msg exec polybar top
  pre:
    plug: nvim +PlugInstall +qall
    plug-inst: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_homepage:
    dst: ~/.config/homepage
    src: config/homepage
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_album-pic.sh:
    dst: ~/.scripts/util/album-pic.sh
    src: scripts/util/album-pic.sh
  f_cava_config:
    dst: ~/.config/cava/config
    src: config/cava/config
  f_compton.conf:
    dst: ~/.compton.conf
    src: compton.conf
  f_config:
    actions:
    - i3-run
    dst: ~/.config/i3/config
    src: config/i3/config
  f_config.py:
    dst: ~/.config/qutebrowser/config.py
    src: config/qutebrowser/config.py
  f_config.py.template:
    dst: ~/.config/qutebrowser/config.py.template
    src: config/qutebrowser/config.py.template
  f_config.template:
    dst: ~/.config/cava/config.template
    src: config/cava/config.template
  f_dunstrc:
    actions:
    - dunst-run
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_dunstrc.template:
    dst: ~/.config/dunst/dunstrc.template
    src: config/dunst/dunstrc.template
  f_init.vim:
    actions:
    - plug-inst
    - plug
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_input.conf:
    dst: ~/.config/mpv/input.conf
    src: config/mpv/input.conf
  f_lock:
    dst: /usr/bin/lock
    src: usr/bin/lock
  f_mpv.conf:
    dst: ~/.config/mpv/mpv.conf
    src: config/mpv/mpv.conf
  f_music.json:
    dst: ~/.config/i3/music.json
    src: config/i3/music.json
  f_polybar_config:
    actions:
    - polybar-run
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_prisma.css:
    dst: ~/Projects/css/Prisma.css
    src: Projects/css/Prisma.css
  f_prisma.css.template:
    dst: ~/Projects/css/Prisma.css.template
    src: Projects/css/Prisma.css.template
  f_profile:
    dst: /etc/profile
    src: etc/profile
  f_profile-switch.sh:
    dst: ~/.scripts/util/profile-switch.sh
    src: scripts/util/profile-switch.sh
  f_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_rifle.conf:
    dst: ~/.config/ranger/rifle.conf
    src: config/ranger/rifle.conf
  f_toggle:
    dst: /usr/bin/toggle
    src: usr/bin/toggle
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_xresources.template:
    dst: ~/.Xresources.template
    src: Xresources.template
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  rice:
    dotfiles: []
    include:
    - work
  the-arch:
    dotfiles:
    - ALL
  work:
    dotfiles: []
    include:
    - the-arch
