actions:
  pre:
    plug: nvim +PlugInstall +qall
    plug-inst: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_init.vim:
    actions:
    - plug-inst
    - plug
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_lock:
    dst: /usr/bin/lock
    src: usr/bin/lock
  f_music.json:
    dst: ~/.config/i3/music.json
    src: config/i3/music.json
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_profile:
    dst: /etc/profile
    src: etc/profile
  f_rc.conf:
    dst: ~/.config/ranger/rc.conf
    src: config/ranger/rc.conf
  f_rifle.conf:
    dst: ~/.config/ranger/rifle.conf
    src: config/ranger/rifle.conf
  f_toggle:
    dst: /usr/bin/toggle
    src: usr/bin/toggle
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  the-arch:
    dotfiles:
    - f_config
    - f_init.vim
    - f_polybar_config
    - f_zshrc
    - f_profile
    - d_scripts
    - f_rc.conf
    - f_rifle.conf
    - f_music.json
    - f_toggle
    - f_lock
